// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brxdgbtgjgztygkwzoki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyeGRnYnRnamd6dHlna3d6b2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDc0NjEsImV4cCI6MjA2OTA4MzQ2MX0.rcbmAsZRN0K4K9RETgrfWBAlywzIloBnGvdQgqy_Gc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});